<?php
$escape = $this->plugin('escapeHtml');
$path =  $_SERVER["REQUEST_URI"];
$parts = explode('/', $path);
$current_locale = $parts[3];
?>
<?php $this->htmlElement('body')->appendAttribute('class', 'item resource browse'); ?>
<?php if (isset($itemSet)): ?>
    <?php $this->htmlElement('body')->appendAttribute('class', 'item-set'); ?>
<?php endif; ?>

<?php if (isset($itemSet)): ?>
    <?php echo $this->pageTitle($itemSet->displayTitle(), 2); ?>
    <?php /*
    <h3><?php echo $this->translate('Item Set'); ?></h3>
    <div class="metadata">
        <?php echo $itemSet->displayValues(); ?>
    </div>
    <?php echo $this->pageTitle($this->translate('Items'), 3); ?>
    */ ?>
<?php else: ?>
    <?php echo $this->pageTitle($this->translate('All collections'), 2); ?>   
<?php endif; ?>

<?php echo $this->searchFilters(); ?>
<?php /*echo $this->hyperlink($this->translate('Advanced search'), $this->url(null, ['action' => 'search'], true), ['class' => 'advanced-search']);*/ ?>
<?php echo $this->pagination(); ?>
<ul class="resource-list">
    <?php foreach ($items as $item): ?>
    <li class="item resource">
        <?php if ($primaryMedia = $item->primaryMedia()): ?>
        <div class="icon"><img
            src="<?php echo $escape($primaryMedia->thumbnailUrl('medium')); ?>"
            title="<?php echo $escape($primaryMedia->displayTitle()); ?>"
            alt="<?php echo $escape($primaryMedia->mediaType()); ?> thumbnail"
        ></div>
        <?php endif; ?>
        <h4><?php echo $item->link($item->displayTitle()); ?></h4>
        
        <?php if ($date = $item->value('dcterms:date')): ?>
        <div class="date"><?php echo $date; ?></div>
        <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
<?php echo $this->pagination(); ?>
<?php $this->trigger('view.browse.after'); ?>
