<div class="preview-block">

<?php if ($this->heading): ?>
<h2><?php echo $this->heading; ?></h2>
<?php endif; ?>

<ul class="resource-list preview">
<?php $count=0 ?>
<?php foreach ($this->items as $item): ?>
    <?php if ($count<2): ?>
        <li class="item resource">
        <?php if ($primaryMedia = $item->primaryMedia()): ?>
            <div class="icon"><img
                src="<?php echo $this->escapeHtml($primaryMedia->thumbnailUrl('medium')); ?>"
                title="<?php echo $this->escapeHtml($primaryMedia->displayTitle()); ?>"
                alt="<?php echo $this->escapeHtml($primaryMedia->mediaType()); ?> thumbnail"
            ></div>
        <?php endif; ?>
            <h4><?php echo $item->link($item->displayTitle()); ?></h4>
            <?php if ($description = $item->displayDescription()): ?>
            <div class="description"><?php echo $description; ?></div>
            <?php endif; ?>
        </li>
        <?php $count ++; ?>
    <?php endif; ?>
<?php endforeach; ?>
</ul>

<?php
$linkText = $this->linkText == '' ? $this->translate('Browse all') : $this->linkText;
echo $this->hyperlink($linkText, $this->url(
    'site/resource', ['controller' => 'item', 'action' => 'browse'], ['query' => $this->query], true
));
?>

</div>
