<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->setAttribute('lang', 'en');
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Crimson+Text:400,400italic,700,700italic');
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/centerrow.js'));
$this->headScript()->prependFile($this->assetUrl('js/jquery.js', 'Omeka'));
$this->trigger('view.layout');
$languages = array('fr' => 'Français',
                'tr' => 'Türkçe', 
                'en'=> 'English');
$path =  $_SERVER["REQUEST_URI"];
$parts = explode('/', $path);
$current_locale = $parts[3];

?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <div id="wrap">
            <header>
                <!-- On the left, display the logo and the title of the website next to each other -->
                <?php if ($this->themeSetting('logo')): ?>
                    <a href="<?php echo $site->url().'/page/welcome' ; ?>" class="site-title"><img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" title="Logo"></a>
                <?php endif; ?>
                <div id="siteTitle">
                    <a href="<?php echo $site->url().'/page/welcome'; ?>" class="site-title"><?php echo $this->pageTitle($site->title()); ?></a>
                    
                    <div id="siteLinks">
                        <a href="<?php echo $site->url().'/page/about' ; ?>" class="site-links"><?php echo $this->translate('About us'); ?></a>
                            --------- 
                            <a href="<?php echo $site->url().'/page/other' ; ?>" class="site-links"><?php echo $this->translate('Other links'); ?></a>
                            --------- 
                            <a href="<?php echo 'http://ifea-istanbul.net/' ; ?>" class="site-links" target="_blank"><?php echo $this->translate('IFEA website'); ?></a>
                    </div>
                </div>

                <!-- In the middle, display the search bar -->
                <div id="search-container">
                    <form action="<?php echo $this->escapeHtml($this->url('site/resource', ['controller' => 'item','action' => 'browse'], true)); ?>" id="search-form" class="open">
                        <?php $searchValue = isset($_GET['property'][0]['in'][0]) ? $_GET['property'][0]['in'][0] : ''; ?>
                        <input type="text" name="property[0][in][]" value="<?php echo $escape($searchValue); ?>" placeholder="<?php echo $this->translate('Search'); ?>">
                        <button type="submit"><?php echo $this->translate('Search'); ?></button>
                    </form>
                </div>        

                <!-- On the right, display the language switcher -->
                <div id="language-switcher">
                        <?php foreach ($languages as $locale => $language): ?>
                            <?php //if ($locale != $current_locale): ?>
                                <a href="<?php 
                                    //echo dirname($site->url()).'/'.$language 
                                    echo str_replace($current_locale,$locale,$path);
                                ?>">
                                    <?php echo $language ?>
                                </a></br>
                            <?php //endif; ?>
                        <?php endforeach; ?>
                </div>
                
                <!-- At the bottom, display the navigation menu -->
                <nav>
                <?php
                echo $site->publicNav()->menu()->renderMenu(null, [
                    'maxDepth' => $this->themeSetting('nav_depth') - 1
                ]);
                ?>
                </nav>

            </header>

            <div id="content" role="main">
                <?php echo $this->content; ?>
            </div>

            <footer>
                <?php /*if ($footerContent = $this->themeSetting('footer')): ?>
                <?php echo $footerContent; ?>
                <?php else: ?>
                    <?php echo $this->translate('Powered by Omeka S'); ?>
                <?php endif; */?>
                <img src="<?php echo $this->themeSettingAssetUrl('logo1'); ?>" title="Logo2">
                <img src="<?php echo $this->themeSettingAssetUrl('logo2'); ?>" title="Logo2">
                <img src="<?php echo $this->themeSettingAssetUrl('logo3'); ?>" title="Logo3">
            </footer>
        </div>
    </body>
</html>
